default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  database: ror_postgres_development

test:
  <<: *default
  database: ror_postgres_test

production:
  <<: *default
  database: ror_postgres_production
  username: deploy
  password: deploy
